---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by parker.
--- DateTime: 2020/5/6 11:19 下午
--- 配置类
---
server = {}

server.address = {
    "192.0.0.1",
    "192.0.0.2",
    "192.0.0.3",
    "192.0.0.4",
    "192.0.0.5"
}

return server